Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'TechDivision.Card.Decks':
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        'TechDivision.Card.Decks': true
TechDivision:
  Card:
    Decks:
      extra:
        translation:
          package: 'TechDivision.Card.Decks'
          source: 'NodeTypes/*'